//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JikagakiDesktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupHelpEnabled {
            get {
                return ((bool)(this["StartupHelpEnabled"]));
            }
            set {
                this["StartupHelpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"直書きデスクトップとは・・・
デスクトップ上にドラッグで線を直接書き込むことができるツールです。
起動時は黒色のペンを持っている状態です。
以下のキー操作が行えます。

P でドラッグで自由線を描くモードに切り替えます。
L でドラッグで直線を描くモードに切り替えます。
F でドラッグで四角を描くモードに切り替えます。
D でドラッグで楕円を描くモードに切り替えます。

B で黒色のペンに持ち替えます。
W で白色のペンに持ち替えます。
R で赤色のペンに持ち替えます。
Y で黄色のペンに持ち替えます。
C で水色のペンに持ち替えます。
G で緑色のペンに持ち替えます。
Space で消しゴムに持ち替えます。

1～9 でペンの太さを切り替えます。

Ctrl+Z で一つ前の状態に戻します。
Delete で書き込みを全て削除します。
Ctrl+S で書き込んだ内容を保存します。
Ctrl+O で保存した内容を復元します。
Esc で待機状態に（最小化）します。
F1 でこの説明を表示します。

Alt + F4 で終了します。")]
        public string StartupHelp {
            get {
                return ((string)(this["StartupHelp"]));
            }
            set {
                this["StartupHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public byte Alpha {
            get {
                return ((byte)(this["Alpha"]));
            }
            set {
                this["Alpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string StartupColor {
            get {
                return ((string)(this["StartupColor"]));
            }
            set {
                this["StartupColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double StartupWidth {
            get {
                return ((double)(this["StartupWidth"]));
            }
            set {
                this["StartupWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string StartupTool {
            get {
                return ((string)(this["StartupTool"]));
            }
            set {
                this["StartupTool"] = value;
            }
        }
    }
}
